{% set name = "PsychoPy" %}
{% set version = "2022.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 17b51c4157559b9c423dde69f9d53da37888df3759572f844ae6a57354725262

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  entry_points:
    - psychopy = psychopy.app.psychopyApp:main
  osx_is_app: true

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - distro  # [linux]
  run:
    - python
    - python.app               # [osx]
    - packaging
    - arabic_reshaper
    - astunparse
    - configobj
    - distro                   # [linux]
    - esprima-python
    - freetype-py
    - future
    - gevent
    - gitpython
    - greenlet
    - hdf5
    - imageio >=2.5
    - imageio-ffmpeg
    - json_tricks
    - matplotlib
    - moviepy
    - msgpack-numpy
    - msgpack-python
    - numpy
    - opencv
    - openpyxl
    - pandas
    - pillow
    - psutil
    - pyglet >=1.4.9
    - glfw                     # [not linux]
    - glfw !=3.3.1             # [linux]
    - javascripthon            # [py>=3.5]
    - pyglfw
    - pyobjc-framework-quartz  # [osx]
    - pyopengl
    - pyosf
    - pyqmix >=2018.12.13      # [not linux]
    - pyqt
    - pyserial
    - pysoundfile              # [not win]
    - pytables
    - python-bidi
    - python-gitlab
    - python-sounddevice
    - pywin32                  # [win]
    - pyWinhook                # [win]
    - pyyaml
    - pyzmq
    - questplus >=2019.3
    - requests
    - scipy
    - websocket-client
    - wxpython !=4.0.2, !=4.0.3
    - xlrd

test:
  files:
    - run_tests.py
  requires:
    - libglu                   # [linux]
  commands:
    # This is to test the entry point.
    - psychopy --version

    # We moved all "import ..." tests to `run_tests.py` because on Linux, we
    # need to run the tests through xvfb-run as most of them require a
    # (virtual) display. On Windows and macOS, we run the script directly.
    # Note that some essential tests are disabled on Linux due to problems with
    # the CI system; see `run_tests.py` for details.

    - python run_tests.py      # [not linux]
    # https://stackoverflow.com/a/30029944/1944216
    - xvfb-run --server-args=":99 -screen 0 1024x768x24 -ac +extension GLX -noreset" python run_tests.py  # [linux]

about:
  home: https://www.psychopy.org
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Psychology experiment software in Python
  description: |
    PsychoPy is an open-source package for creating psychology stimuli in
    Python (A real and free alternative to Matlab). PsychoPy combines the
    graphical strengths of OpenGL with the easy Python syntax to give
    psychophysics a free and simple stimulus presentation and control package.
  doc_url: https://www.psychopy.org/documentation.html
  dev_url: https://github.com/psychopy/psychopy

extra:
  recipe-maintainers:
    - kastman
    - peircej
    - hoechenberger
