travis:
  secure:
    BINSTAR_TOKEN: p08RImZyYa22lkZRcogZa9t5KO+ojo3M5LsAB4sjSpZP2HEPXelz6Om0RivrY6d/iQfptA0YAQR8g9msPy96YGFj/oGF8ltuhhT/qTPMux4NF8E5DtV8rALrTzdOctw4iJSgDpp7jsyObRj3iSwCCVWEqF301UoRkXpdoafJTPlzRzP8jrFtfNDpV5jCULDUGG6/1+rEoMla7QJaEibOViH6ROxj4BAbGt8GO9UmVFXQiWU64m6MOhqA3OEyylkhXHvKahIn0EM4foZ8Hqet4oLmbhXpmv5AiPeB+lAuHcgdV+lQKf3iQAF6CZC9/1emOnIjxSNNCiPmvCR7stX7KY+4v0RNAE0udEPm9V77H7lZRSVZEOI1yQXBoHBQ0Oj1sW+8J9UEhH3un/Wbm6cOekh1M8tMLNDdxVGcPQcPKEkE0NaDDKavdpB3BYxf/w4zBGQXXCnjuyzs1VBZn8xeK5F6abIYJBWRmepYLh1+xWvkir+dM8WgxfC8RhJnuuJrzV/KCK2BLusgqlSc/wPrvF7isSkYRYKdd/5dG5l/bR7WjdHieIMH9KftfaVYc2dOe3FpbrkFpP4KdIYDTbMna9ULfy+GL2Z6bqBnRMgqKDl7oxdb9asGdVVsrnSGj9wz58k+zTzGSlA+kn1do2kB1FxbDlLVy7/c/BaD3E9YwKU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
